# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='age',
            name='age_text',
        ),
    ]
