# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170522_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
