# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170523_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
    ]
